### PR TITLE
[#6] Support Proxies That Set Additional Cookies

### LINKED ISSUE #6: cli: Wrong Cookie Gets Saved When Used w/ Cloudflare
Hey, I set `intray-server` up on a VPS which is secured by Cloudflare. When you use Cloudflare's proxy/SSL service, they add a `__cfduid` cookie to responses. It seems like intray just records the first cookie it sees, so the actual JWT cookie never gets saved:

```
$ intray login
$ cd ~/.cache/intray
$ cat session.cookie
__cfduid=REDACTED; Path=/; Expires=Tue, 19-May-2020 11:07:48 GMT; Domain=.REDACTED.com; HttpOnly; Secure
$ intray sync
Sync failed:
FailureResponse 
  (Request {requestPath = (BaseUrl {baseUrlScheme = Https, baseUrlHost = "REDACTED", baseUrlPort = 443, baseUrlPath = ""},"/intray/sync"), requestQueryString = fromList [], requestBody = Just ((),application/json;charset=utf-8), requestAccept = fromList [application/json;charset=utf-8,application/json], requestHeaders = fromList [("Authorization","Bearer REDACTED")], requestHttpVersion = HTTP/1.1, requestMethod = "POST"}) 
  (Response {responseStatusCode = Status {statusCode = 401, statusMessage = "Unauthorized"}, responseHeaders = fromList [("Date","Sun, 19 Apr 2020 11:07:52 GMT"),("Content-Length","0"),("Connection","keep-alive"),("Set-Cookie","__cfduid=REDACTED; expires=Tue, 19-May-20 11:07:52 GMT; path=/; domain=.REDACTED; HttpOnly; SameSite=Lax"),("CF-Cache-Status","DYNAMIC"),("Expect-CT","max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\""),("Server","cloudflare"),("CF-RAY","58662a17dcecbe78-RIC"),("cf-request-id","0233b8a2e60000be782f99f200000001")], responseHttpVersion = HTTP/1.1, responseBody = ""})
```

If I disable the proxy service and login via `http` instead of https, it works and then I can switch cloudflare back on. It seems like the android client is not affected by this issue.

### PR DESCRIPTION
**Pull request by prikhi**
This fixes the CLI client & I'm currently building this to test the `intray-server` changes. I don't use the web-server, so logging in via that should be tested as well.

Similar changes are needed to fix `smos-server` and `tickler-server`.

Commit message follows:

---

Add support for using the CLI client with proxied servers that append
their own cookies to the `Set-Cookie` header returned by the `PostLogin`
API route.

For example, servers proxied behind CloudFlare will get a __cfuid cookie
appended to the Set-Cookie header. Previously, the client would
incorrectly save the __cfuid cookie to the session.cookie file. We
prevent this by having the client's PostLogin handler parse the Cookies
itself, locate the correct `JWT-Cookie` cookie, and explicitly save
that cookie, instead relying on Servant's SetCookie parsing which simply
parses the first cookie it sees.

We also collapse the double "Set-Cookie" Header in the PostLogin API
route since it is no longer necessary.

Closes #6

### CODE REVIEW

**Comment by NorfairKing** [comment]
> This fixes the CLI client & I'm currently building this to test the intray-server changes. I don't use the web-server, so logging in via that should be tested as well.

The web server uses the server and it uses `intray-client` so that should "Just work", but it's also tested on CI.

> Similar changes are needed to fix smos-server and tickler-server.

Indeed, but let's see if this fixes your issue.

File: intray-server/src/Intray/Server/Handler/Public/PostLogin.hs [hunk 1]
```diff
@@ -55,10 +56,10 @@ servePostLogin LoginForm {..} = do
...
-      case mApplyCookies of
+      mCookie <- liftIO $ makeSessionCookieBS envCookieSettings envJWTSettings cookie
+      case mCookie of
         Nothing -> throwError err401
-        Just applyCookies -> do
+        Just setCookie -> do
           now <- liftIO getCurrentTime
           runDb $ update uid [UserLastLogin =. Just now]
-          return $ applyCookies NoContent
+          return $ addHeader (decodeUtf8 setCookie) NoContent
```
Comment (NorfairKing) [inline intray-server/src/Intray/Server/Handler/Public/PostLogin.hs:65]: `decodeUtf8` can fail. Are you sure the `setCookie` is `UTF8` encoded? If so, please make a comment that points to where it says so.
I assume the docs of `makeSessionCookieBS`.
Alternatively, isn't there a `makeSessionCookieText`?

**Comment by NorfairKing** [comment]
Entirely aside: If you run your own intray (,tickler, or smos for that matter) server, please consider sponsoring me on github. I make some (small) amount of money from users on intray.eu etc, but am otherwise not being paid for my work here.

File: intray-server/src/Intray/Server/Handler/Public/PostLogin.hs (hunk 1 above)
Comment (prikhi) [reply intray-server/src/Intray/Server/Handler/Public/PostLogin.hs:65]: Unfortunately, there is no `makeSesionCookieText` :(

I'm not entirely sure it will always be UTF8, but section 7.1 of the [JWT RFC](https://tools.ietf.org/html/rfc7519) seems to indicate that the message should be UTF-8.

**Comment by prikhi** [comment]
> Entirely aside: If you run your own intray (,tickler, or smos for that matter) server, please consider sponsoring me on github. I make some (small) amount of money from users on intray.eu etc, but am otherwise not being paid for my work here.

I would just use intray.eu if I could, but I've taken a vow of poverty so funds are always limited :frowning_face: 
I'll just be using this personally, I don't plan on advertising or competing with intray.eu.

**Comment by prikhi** [comment]
(force pushed after running indent on source)

**Comment by prikhi** [comment]
Also, the test run on our server seems to work fine.

**Comment by NorfairKing** [comment]
> I would just use intray.eu if I could, but I've taken a vow of poverty so funds are always limited frowning_face
> I'll just be using this personally, I don't plan on advertising or competing with intray.eu.

No worries, and don't feel bad about it.
I'm grateful for your help and bug reports.
